import { useEffect, useRef, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { api, ApiError, type ExperienceLevel, type LearningGoal } from '../api'
import GenerationProgress from '../components/GenerationProgress'

const LEVELS: { value: ExperienceLevel; label: string }[] = [
  { value: 'BEGINNER', label: 'Beginner' },
  { value: 'INTERMEDIATE', label: 'Intermediate' },
  { value: 'ADVANCED', label: 'Advanced' },
]

const GOALS: { value: LearningGoal; label: string }[] = [
  { value: 'GENERAL_UNDERSTANDING', label: 'General understanding' },
  { value: 'BUILD_A_PROJECT', label: 'Build a project' },
  { value: 'SYSTEM_DESIGN_INTERVIEW', label: 'System design interview' },
  { value: 'JOB_INTERVIEW', label: 'Job interview' },
  { value: 'UNIVERSITY_COURSE', label: 'University course' },
]

export default function LandingPage() {
  const navigate = useNavigate()
  const [topic, setTopic] = useState('')
  const [context, setContext] = useState('')
  const [level, setLevel] = useState<ExperienceLevel>('BEGINNER')
  const [goal, setGoal] = useState<LearningGoal>('GENERAL_UNDERSTANDING')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)

  // Navigating away while a generation is in flight must not yank the user back when it
  // lands. Without this, starting a generation and then opening another page dumped you onto
  // the roadmap up to a minute later, wherever you had gone.
  // Set on mount as well as cleared on unmount: StrictMode runs effects mount/cleanup/mount,
  // so initialising the ref alone leaves it false after the first cleanup and navigation
  // never happens again.
  const live = useRef(true)
  useEffect(() => {
    live.current = true
    return () => { live.current = false }
  }, [])

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    if (!topic.trim() || busy) return
    setBusy(true)
    setError(null)
    try {
      const roadmap = await api.generate(topic.trim(), context.trim(), level, goal)
      if (live.current) navigate(`/r/${roadmap.shareToken}`)
    } catch (err) {
      if (live.current) {
        setError(err instanceof ApiError ? err.message : 'Something went wrong. Please try again.')
      }
    } finally {
      if (live.current) setBusy(false)
    }
  }

  return (
    <section className="landing">
      <h1>What do you want to understand?</h1>
      <p className="tagline">
        Uncomplex doesn't teach you the topic — it tells you what to learn <em>first</em>,
        in order, with credible resources.
      </p>

      <form className="card generate-form" onSubmit={handleSubmit}>
        <label>
          Topic
          <input
            value={topic}
            onChange={e => setTopic(e.target.value)}
            placeholder="Rate limiting, Docker, OAuth, database indexing…"
            maxLength={120}
            required
          />
        </label>

        {/* The hint is a description, not part of the accessible name — keeping it inside the
            label would fold it into the name and make "Topic" ambiguous to match. */}
        <div className="field">
          <label>
            In the context of <span className="label-optional">optional</span>
            <input
              value={context}
              onChange={e => setContext(e.target.value)}
              placeholder="CI/CD pipelines, REST APIs, data engineering…"
              maxLength={120}
              aria-describedby="context-hint"
            />
          </label>
          <p id="context-hint" className="hint">
            Some subjects mean different things in different places. &ldquo;Integration&rdquo; is
            CI/CD to one person and REST APIs to another — say which you meant and you get a
            roadmap for that one.
          </p>
        </div>

        <div className="form-row">
          <label>
            Current level
            <select value={level} onChange={e => setLevel(e.target.value as ExperienceLevel)}>
              {LEVELS.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
            </select>
          </label>

          <label>
            Learning goal
            <select value={goal} onChange={e => setGoal(e.target.value as LearningGoal)}>
              {GOALS.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
            </select>
          </label>
        </div>

        <button type="submit" disabled={busy}>
          {busy ? 'Building your path…' : 'Build my learning path'}
        </button>

        {busy && <GenerationProgress topic={topic.trim()} />}

        <p className="hint ai-notice">
          Generated by AI, so it can be incomplete or wrong — and every roadmap gets a public link,
          so keep topics non-sensitive. <Link to="/terms">How this works</Link>
        </p>

        {error && <p className="error">{error}</p>}
      </form>
    </section>
  )
}
