const UPDATED = '6 September 2026'

export default function TermsPage() {
  return (
    <section className="legal">
      <h1>Terms and AI disclosure</h1>
      <p className="muted">Last updated {UPDATED}</p>

      <h2>Roadmaps are generated by an AI model</h2>
      <p>
        Every roadmap on this site is produced by a large language model (Anthropic&apos;s Claude) in
        response to the topic you type. Nobody reviews it before you see it. The model decides which
        concepts matter, what order they belong in, and how long each might take.
      </p>
      <p>
        That means a roadmap can be <strong>incomplete, mis-ordered, or simply wrong</strong>. Time
        estimates are guesses. A concept you actually need may be missing, and one you do not need may
        be included. Treat the output as a starting point to think from, not an authority to follow.
      </p>

      <h2>What the credibility check does and does not do</h2>
      <p>
        Resource links are filtered against an allowlist of trusted domains — official documentation,
        standards bodies, universities and recognised educational sites. This checks{' '}
        <strong>the domain only</strong>.
      </p>
      <p>
        It does <strong>not</strong> verify that the page exists, that it is about the right subject,
        or that its contents are accurate. A link on an approved domain can still be wrong or dead. A
        separate background check periodically tests whether links still respond, and links it has not
        reached yet are labelled <em>link not yet checked</em>. Judge sources for yourself.
      </p>

      <h2>Not professional advice</h2>
      <p>
        Uncomplex offers general educational suggestions. It is not career, academic, financial,
        medical or legal advice, and it is not a substitute for a qualified instructor or a formal
        curriculum. Decisions you make on the basis of a generated roadmap are your own.
      </p>

      <h2>Acceptable use</h2>
      <ul>
        <li>Do not submit personal, confidential or sensitive information as a topic — roadmaps are public.</li>
        <li>Do not attempt to overwhelm, probe or circumvent the service&apos;s request limits.</li>
        <li>Do not use it to generate content that is unlawful or that infringes someone else&apos;s rights.</li>
      </ul>
      <p>
        Generation is rate-limited per visitor. Exceeding the limit returns an error and you can try
        again later.
      </p>

      <h2>Availability and warranty</h2>
      <p>
        This is a personal portfolio project running on free hosting. It may be slow to wake, may go
        offline without notice, and may lose data. It is provided <strong>as is</strong>, without
        warranty of any kind, and no liability is accepted for any loss arising from its use or
        unavailability. Do not rely on it as your only record of anything.
      </p>

      <h2>Your content and your account</h2>
      <p>
        Generated roadmaps are shared, public and permanent — they remain available by link even after
        the account that generated one is deleted, because other people may have saved them. You can
        delete your account, library and progress at any time from <em>My roadmaps</em>. See the{' '}
        privacy policy for what that removes.
      </p>
    </section>
  )
}
