package com.uncomplex.roadmap.model;

public enum SourceType {
    OFFICIAL_DOCUMENTATION,
    STANDARDS_ORGANIZATION,
    UNIVERSITY_MATERIAL,
    EDUCATIONAL_ORGANIZATION,
    TECHNICAL_PUBLICATION,
    RECOGNIZED_CREATOR
}
