CREATE TABLE roadmap (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cache_key               VARCHAR(255)  NOT NULL,
    share_token             VARCHAR(64)   NOT NULL,
    topic                   VARCHAR(160)  NOT NULL,
    title                   VARCHAR(255)  NOT NULL,
    summary                 VARCHAR(2000) NOT NULL,
    experience_level        VARCHAR(20)   NOT NULL,
    goal                    VARCHAR(40)   NOT NULL,
    estimated_total_minutes INT           NOT NULL,
    created_at              TIMESTAMP     NOT NULL,
    CONSTRAINT uq_roadmap_cache_key UNIQUE (cache_key),
    CONSTRAINT uq_roadmap_share_token UNIQUE (share_token)
);

CREATE TABLE roadmap_node (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    roadmap_id        BIGINT        NOT NULL,
    name              VARCHAR(160)  NOT NULL,
    description       VARCHAR(2000) NOT NULL,
    reason            VARCHAR(2000) NOT NULL,
    difficulty        VARCHAR(20)   NOT NULL,
    estimated_minutes INT           NOT NULL,
    order_index       INT           NOT NULL,
    CONSTRAINT fk_node_roadmap FOREIGN KEY (roadmap_id) REFERENCES roadmap (id) ON DELETE CASCADE
);

CREATE TABLE node_resource (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id            BIGINT        NOT NULL,
    title              VARCHAR(255)  NOT NULL,
    url                VARCHAR(1000) NOT NULL,
    source_type        VARCHAR(40)   NOT NULL,
    credibility_reason VARCHAR(500)  NOT NULL,
    CONSTRAINT fk_resource_node FOREIGN KEY (node_id) REFERENCES roadmap_node (id) ON DELETE CASCADE
);

CREATE INDEX idx_node_roadmap ON roadmap_node (roadmap_id);
CREATE INDEX idx_resource_node ON node_resource (node_id);
