CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    created_at    TIMESTAMP    NOT NULL,
    CONSTRAINT uq_user_email UNIQUE (email)
);

-- A user's library: which shared roadmaps they follow. Roadmaps themselves stay
-- immutable and shared across users (one AI generation per topic/level/goal).
CREATE TABLE saved_roadmap (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT    NOT NULL,
    roadmap_id BIGINT    NOT NULL,
    saved_at   TIMESTAMP NOT NULL,
    CONSTRAINT fk_saved_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_saved_roadmap FOREIGN KEY (roadmap_id) REFERENCES roadmap (id) ON DELETE CASCADE,
    CONSTRAINT uq_saved_user_roadmap UNIQUE (user_id, roadmap_id)
);

-- Per-user completion of individual roadmap nodes.
CREATE TABLE node_progress (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT    NOT NULL,
    node_id      BIGINT    NOT NULL,
    completed_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_progress_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_progress_node FOREIGN KEY (node_id) REFERENCES roadmap_node (id) ON DELETE CASCADE,
    CONSTRAINT uq_progress_user_node UNIQUE (user_id, node_id)
);

CREATE INDEX idx_saved_user ON saved_roadmap (user_id);
CREATE INDEX idx_progress_user ON node_progress (user_id);
