-- Link liveness: resources are probed on a schedule; NULL = never checked yet.
ALTER TABLE node_resource ADD COLUMN reachable BOOLEAN;
ALTER TABLE node_resource ADD COLUMN last_checked_at TIMESTAMP;

-- Refresh tokens: only the SHA-256 hash is stored; the raw token exists client-side only.
CREATE TABLE refresh_token (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP   NOT NULL,
    created_at TIMESTAMP   NOT NULL,
    revoked_at TIMESTAMP,
    CONSTRAINT fk_refresh_user FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE,
    CONSTRAINT uq_refresh_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_refresh_user ON refresh_token (user_id);
